export const scaleNumbers = [
  { question: 'What number is the note A on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note B on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note C on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note D on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note E on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note F on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note G on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note A on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note B on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note C on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note D on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note E on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note F on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note G on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note A on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note B on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note C on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note D on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note E on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note F on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note G on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note A on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note B on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note C on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note D on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note E on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note F on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note G on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note A on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note B on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note C on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note D on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note E on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note F on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note G on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note A on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note B on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note C on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note D on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note E on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note F on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note G on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note A on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note B on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note C on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note D on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note E on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note F on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note G on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What note is I on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is II on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is III on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is IV on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is V on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is VI on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is VII on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is I on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is II on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is III on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is IV on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is V on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is VI on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is VII on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is I on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is II on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is III on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is IV on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is V on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is VI on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is VII on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is I on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is II on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is III on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is IV on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is V on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is VI on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is VII on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is I on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is II on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is III on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is IV on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is V on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is VI on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is VII on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is I on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is II on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is III on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is IV on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is V on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is VI on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is VII on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is I on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is II on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is III on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is IV on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is V on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is VI on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is VII on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
];
