export const scaleNumbers = [
  { question: 'What number is the note A on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note B on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note C on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note D on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note E on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note F on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note G on the A scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note A on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note B on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note C on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note D on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note E on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note F on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note G on the B scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note A on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note B on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note C on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note D on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note E on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note F on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note G on the C scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note A on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note B on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note C on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note D on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note E on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note F on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note G on the D scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note A on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note B on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note C on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note D on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note E on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note F on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note G on the E scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note A on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note B on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note C on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note D on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note E on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note F on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What number is the note G on the F scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note A on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'II' },
  { question: 'What number is the note B on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'III' },
  { question: 'What number is the note C on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'IV' },
  { question: 'What number is the note D on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'V' },
  { question: 'What number is the note E on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VI' },
  { question: 'What number is the note F on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'VII' },
  { question: 'What number is the note G on the G scale?', answers: ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII'], correctAnswer: 'I' },
  { question: 'What note is I on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is II on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is III on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is IV on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is V on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is VI on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is VII on the A scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is I on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is II on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is III on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is IV on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is V on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is VI on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is VII on the B scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is I on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is II on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is III on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is IV on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is V on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is VI on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is VII on the C scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is I on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is II on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is III on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is IV on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is V on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is VI on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is VII on the D scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is I on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is II on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is III on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is IV on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is V on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is VI on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is VII on the E scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is I on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What note is II on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is III on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is IV on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is V on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is VI on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is VII on the F scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is I on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What note is II on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What note is III on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What note is IV on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What note is V on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What note is VI on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What note is VII on the G scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
];

export const scaleQualities = [
  { question: 'What are the qualities of the Major scale?', answers: ['♮3 ♮7', '♭3 ♭5', '♭3 ♭5 ♭♭7', '♮3 ♭7', '♭3 ♭5 ♭7'], correctAnswer: '♮3 ♮7' },
  { question: 'What are the qualities of the Minor scale?', answers: ['♮3 ♮7', '♭3 ♭5 ♭♭7', '♭3 ♭5', '♮3 ♭7', '♭3 ♭5 ♭7'], correctAnswer: '♭3 ♭5' },
  { question: 'What are the qualities of the Dominant 7th scale?', answers: ['♮3 ♮7', '♭3 ♭5 ♭♭7', '♭3 ♭5', '♮3 ♭7', '♭3 ♭5 ♭7'], correctAnswer: '♮3 ♭7' },
  { question: 'What are the qualities of the Diminished scale?', answers: ['♮3 ♮7', '♭3 ♭5 ♭♭7', '♭3 ♭5', '♮3 ♭7', '♭3 ♭5 ♭7'], correctAnswer: '♭3 ♭5 ♭♭7' },
  { question: 'What are the qualities of the Half Diminished scale?', answers: ['♮3 ♮7', '♭3 ♭5 ♭♭7', '♭3 ♭5', '♮3 ♭7', '♭3 ♭5 ♭7'], correctAnswer: '♭3 ♭5 ♭7' },
];

export const specificScaleQualities = [
  { question: 'What is flatted on the A Minor scale?', answers: ['A & C', 'B & D', 'C & E', 'D & F', 'E & G'], correctAnswer: 'C & E' },
  { question: 'What is flatted on the B Minor scale?', answers: ['B & D', 'C & E', 'D & F', 'E & G', 'F & A'], correctAnswer: 'D & F' },
  { question: 'What is flatted on the C Minor scale?', answers: ['C & E', 'D & F', 'E & G', 'F & A', 'G & B'], correctAnswer: 'E & G' },
  { question: 'What is flatted on the D Minor scale?', answers: ['D & F', 'E & G', 'F & A', 'G & B', 'A & C'], correctAnswer: 'F & A' },
  { question: 'What is flatted on the E Minor scale?', answers: ['E & G', 'F & A', 'G & B', 'A & C', 'B & D'], correctAnswer: 'G & B' },
  { question: 'What is flatted on the F Minor scale?', answers: ['F & A', 'G & B', 'A & C', 'B & D', 'C & E'], correctAnswer: 'A & C' },
  { question: 'What is flatted on the G Minor scale?', answers: ['G & B', 'A & C', 'B & D', 'C & E', 'D & F'], correctAnswer: 'B & D' },
  { question: 'What is flatted on the A Dominant 7th scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'G' },
  { question: 'What is flatted on the B Dominant 7th scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'A' },
  { question: 'What is flatted on the C Dominant 7th scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'B' },
  { question: 'What is flatted on the D Dominant 7th scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'C' },
  { question: 'What is flatted on the E Dominant 7th scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'D' },
  { question: 'What is flatted on the F Dominant 7th scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'E' },
  { question: 'What is flatted on the G Dominant 7th scale?', answers: ['A', 'B', 'C', 'D', 'E', 'F', 'G'], correctAnswer: 'F' },
  { question: 'What is flatted on the A Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'C, E, & G' },
  { question: 'What is flatted on the B Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'D, F, & A' },
  { question: 'What is flatted on the C Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'E, G, & B' },
  { question: 'What is flatted on the D Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'F, A, & C' },
  { question: 'What is flatted on the E Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'G, B, & D' },
  { question: 'What is flatted on the F Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'A, C, & E' },
  { question: 'What is flatted on the G Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'B, D, & F' },
  { question: 'What is flatted on the A Half Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'C, E, & G' },
  { question: 'What is flatted on the B Half Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'D, F, & A' },
  { question: 'What is flatted on the C Half Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'E, G, & B' },
  { question: 'What is flatted on the D Half Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'F, A, & C' },
  { question: 'What is flatted on the E Half Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'G, B, & D' },
  { question: 'What is flatted on the F Half Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'A, C, & E' },
  { question: 'What is flatted on the G Half Diminished scale?', answers: ['A, C, & E', 'B, D, & F', 'C, E, & G', 'D, F, & A', 'E, G, & B'], correctAnswer: 'B, D, & F' },
];
